### ISSUE TITLE
Usage in hosted environment

### ISSUE THREAD

**Issue by pabloroz** [cmather/meteor-file#1]
Can I use this in a site hosted in meteor.com?

As far as I understood I should not upload files to the public folder because it will restart the server and I think I cannot upload files in other folders if I dont have access to them.

So can I use this to upload images in a site hosted in meteor.com?

**Comment by cmather** [comment]
Right now this use case isn't easily supported. If you don't control the server you probably want to be saving the files to s3 or some other cloud storage. I'll be adding some better support for this in the near future.

**Comment by pabloroz** [comment]
Thanks, will explore other options to upload the files to s3!
