### ISSUE TITLE
Unique image name

### ISSUE THREAD

**Issue by EnchanterIO** [cmather/meteor-file#3]
Hi. I know you know the image name for every uploaded image is not unique. I think its very important to implement it there.

I was playing with it like 2hours but could not find the right way :( When i uploaded image and assign a  new name to it it always created few new images during the upload. 

Could you please implement it there? I tried different places but still the same mistake ... a lot of files. 

The easiest way would be just before everything start modify the file.name just after event for input change fires.. but somehow its not changable?

Thx great work so far.

**Comment by dadeef** [comment]
You could check if the file already exist using the node fs module and use a new uuid as filename if it does.

**Comment by EnchanterIO** [comment]
Hm... i am not sure what you mean exactly by uuid and the difference between id i saw it the code somewhere but hm... i just get another idea when i will come to home i will try it and will post here a result.

**Comment by EnchanterIO** [comment]
Okay solved. If someone will want have easy solution give me know :+1:
