### ISSUE TITLE
Progress crash

### ISSUE THREAD

**Issue by EnchanterIO** [cmather/meteor-file#4]
Hi, dont know if its just my flaw but when i try to upload file about 2MB everything goes well. But when i try upload file 96MB big.. i get to the about 46% of progress and then it just crash (no errors in both consoles) but  the file disappear from the table like refresh would happened. 
- One more thing. You are saving your file to the disk of PC. But usally we need to save it to the public directory which is watching by meteor and refreshing the page when we save a file there so it automaticly refresh the page after first hit of the folder and then it refuse other things :(... I googled this issue and it should be fixed somehow in future but what to do for now? How to solve it? Its a big issue because that way i cant upload images like 3MB ... the browser refresh earlier then the upload completes.

I know when you add a ~ to the end of folder it will not be watched by meteor but then it crushs the upload by "no dir to upload".

**Comment by cmather** [comment]
Hi there. If you can post a small reproducible example I'll take a look.
Does the browser crash? Do any bytes get written on the server?

**Comment by EnchanterIO** [comment]
Hi, Hm.. i am not sure about the example because during the upload i was checking at once the server console, browser console and folder but without errors. Maybe a video? I changed a little be your gr8 package to image upload only so this is not a big problem for me now because images are usally less then 3MB so easy peasy. 

Could you please answer on my "public folder" part of the issue? :)
